---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: laravel-secrets
  namespace: uniselec-api-stg
spec:
  encryptedData:
    APP_KEY: AgCBKO/UubkHG6OLpwOTivUPR5BWVdsnNY2XzQxMSDwhfeqNNijyU5VtJrQSnzYELuNePpZQBeVSDcAO6NUxxjM2CNo4ofESoiMBrwE+TQlfrTi5Ly/0p3qlIq0WQZcvOiUpSfLg8SbHakf/9LfTw5t5IGrTl160jpmtHpHSopHW7xIewPvSap/0Fa68YDIrO+jHqE3LYzKNCoyPITXPlaneyg9HZY1ssIxAjsCkOY0ZnOfxaj5DH2plcZhh0bWpchdn6p0CUg+17L+KyaO4oNe0yVWqEQFRHohwAneDOcdak22Fi0teB/PYfHL4iu2YAqJSJUjLrJpccGDhyYDyJJc7yLJsqqjhVxSwP3sGKK2/GK5tjsSPD1EQ7PmAU172mc83lxhfDxT8yNxhEkGRlGh6nu++ZRxNuhZW69mre8Qpku41mN1JfeNB2ABfLOSc8b44y1uUb2BAwjKPVomVcSV1JK/LCRj8i5BtS2+AEHbxrgidikTlHFeqTA1AELHNNucPbEWfCjYvarDHzGL92QFJ4PscNnc5pUpJ1EwI8UZq8rVt2YFzJv4s8nFg+N5ZQsXR1PecvFNvqGfe1ZKD8NS+PO27DlF1C5dnGNhbOWyACHNFfee8rDIHZoJ5/k/clsby7S6wGe7JfJrKCY5yExzWXmiDaTWJKdcvjUbTR/J4wBIb7XK7wZ2/J5GcnAI8Jh3rolYo8K+eLIfnaXhoM4jnXNiIy3mi9nLnaJHkPC23VDATTrwQkujzpTbfTVNL3LNXOgk=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: laravel-secrets
      namespace: uniselec-api-stg
    type: Opaque
