apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
spec:
  volumeClaimTemplates:
    - metadata:
        name: database
        labels:
          app: mariadb
        annotations:
          nfs.io/storage-path: ""
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 25Gi
        storageClassName: nfs-storage-k8s-v1
        volumeMode: Filesystem
