apiVersion: v1
kind: ServiceAccount
metadata:
  name: mariadb
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mariadb
rules:
- apiGroups: [ "" ]
  resources: [ "pods" ]
  verbs: [ "get", "list", "watch", "patch", "delete" ]
- apiGroups: [ "batch" ]
  resources: [ "jobs" ]
  verbs: [ "get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mariadb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mariadb
subjects:
- kind: ServiceAccount
  name: mariadb
