apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
spec:
  volumeClaimTemplates:
  - metadata:
      name: database
      labels:
        app: mariadb
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: nfs-storage-k8s-v1