apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
spec:
  template:
    spec:
      containers:
        - name: mariadb
          resources:
            requests:
              cpu: "150m"
              memory: "128Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"