apiVersion: batch/v1
kind: CronJob
metadata:
  name: mariadb-backup-daily
  labels:
    app: mariadb
    component: backup
spec:
  schedule: "0 2 * * *"  # 02:00 AM diariamente
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: mariadb-backup
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchLabels:
                    statefulset.kubernetes.io/pod-name: mariadb-1
                topologyKey: kubernetes.io/hostname
          containers:
          - name: backup
            image: mariadb:10.11.15-jammy
            command: ["/bin/bash", "/scripts/backup-galera-automated.sh"]
            envFrom:
            - secretRef:
                name: mariadb-secret-env
            env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            volumeMounts:
            - name: backup-storage
              mountPath: /backup
            - name: backup-scripts
              mountPath: /scripts
            - name: mysql-data
              mountPath: /var/lib/mysql
              readOnly: true
            resources:
              requests:
                memory: "1Gi"
                cpu: "500m"
              limits:
                memory: "2Gi"
                cpu: "1"
          restartPolicy: OnFailure
          volumes:
          - name: backup-storage
            persistentVolumeClaim:
              claimName: backup-mariadb-1
          - name: backup-scripts
            configMap:
              name: mariadb-backup-scripts
              defaultMode: 0755
          - name: mysql-data
            persistentVolumeClaim:
              claimName: database-mariadb-1