apiVersion: batch/v1
kind: Job
metadata:
  name: mariadb-restore-admin
  labels:
    app: mariadb
    component: restore
spec:
  template:
    spec:
      serviceAccountName: mariadb-backup
      containers:
      - name: restore-admin
        image: mariadb:10.11.15-jammy
        command: ["/bin/bash", "-c"]
        args:
        - |
          echo "================================================================"
          echo "         MARIADB GALERA RESTORE ADMIN - AMBIENTE UNIFICADO      "
          echo "================================================================"
          echo ""
          echo "Este ambiente tem acesso a:"
          echo "  - Backups AUTOMÁTICOS (CronJob): /backup/auto-*"
          echo "  - Backups MANUAIS (Scripts): /backup/manual-*"
          echo "  - PVC: backup-mariadb-1 (mesmo que backup manual usa)"
          echo ""
          echo "COMANDOS DISPONÍVEIS:"
          echo "  /scripts/list-backups.sh           - Lista todos os backups"
          echo "  /scripts/verify-backup.sh <id>     - Verifica integridade"
          echo "  /scripts/execute-restore-safe.sh <id> - Executa restore"
          echo ""
          echo "EXEMPLO:"
          echo "  /scripts/list-backups.sh"
          echo "  /scripts/verify-backup.sh 20251130-124024"
          echo "  /scripts/execute-restore-safe.sh 20251130-124024"
          echo ""
          echo "================================================================"
          echo ""
          echo "Aguardando comandos... (pod ficará ativo)"
          tail -f /dev/null
        envFrom:
        - secretRef:
            name: mariadb-secret-env
        volumeMounts:
        - name: backup-storage
          mountPath: /backup
        - name: backup-scripts
          mountPath: /scripts
        - name: mysql-data
          mountPath: /var/lib/mysql
        securityContext:
          runAsUser: 0
          privileged: true
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
      restartPolicy: Never
      volumes:
      - name: backup-storage
        persistentVolumeClaim:
          claimName: backup-mariadb-1
      - name: backup-scripts
        configMap:
          name: mariadb-backup-scripts
          defaultMode: 0755
      - name: mysql-data
        persistentVolumeClaim:
          claimName: database-mariadb-0