# base/mariadb/backup-restore/pvc-backup-storage.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-backup-pvc
  labels:
    app: mariadb
    component: backup
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: nfs-storage-k8s-v1