apiVersion: v1
kind: ServiceAccount
metadata:
  name: mariadb-backup
  labels:
    app: mariadb
    component: backup

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mariadb-backup
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec"]
  verbs: ["get", "list", "create", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "create", "delete"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mariadb-backup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mariadb-backup
subjects:
- kind: ServiceAccount
  name: mariadb-backup