---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: laravel-secrets
  namespace: uniselec-api
spec:
  encryptedData:
    APP_KEY: AgAKd5SCM5/bReK+N1nUma12DQcl7URBTAwQPYxif9vJsdcN0sbxhBDd5ywvXmMOnASDZRBeJwN961cGm1sxaU4rzIQe9pl6KD0CY7MEboS6eQSJdiqaJwZs8TGkCP3uz5uT3aNv9z72XVDJUbTLwY5rUiiRFAzAwBWayEd59hHueSs61bXd8Mf7xKeAO+rnq4U6X3xRvXtP2zeVgemxYzLZDgeqKhpJtO5K57P4lJh2ROulngT4JT0FZdrPQF7eFK70n+1zRxcasZhkHg81yGv8krrCJ7/EXe2FM8nZt6NCvoE5NEBj7i9JQdE2gLPXOvV6200w/x5+EVOw1Dt+zAIT8gXcgzTXoCWfqOJOQ47BhURjpMpGQJjiPa8Jn7Q7nwFjObXyeRrUBTVqA4Pwk363fvhiAetJW95kmrP6b4MNjUUMIJxLBg8kCqDuhD5Om1cR/7gFZuvRTCKj+//pmgvHhbKcqv6q31UQfZ83ii0Fgw8AxiplSpXUIk7Cx/QKqIv1iwkzIkHWqbSNcupyS4aUeEKrjUAJyE4ndxvj80UyYjXAQkA5N7nmXo6M562PCCVhKOAJR8edchKoZT1XElObmVGf+ozKoSdA5vQG5N7DgUaUgi4qppACztbjeTcMN9h2FoAZrQmlEsBeNUuR470rZ1GE0oBiqXswSNGNdr03uBBGlbDPqNKdXHWNMIDNoL9mO/5l5RKipqEGzq/gCrKKybMruiTTvZGefY+P7pimoQFVTV1R6kPLDa2P7bYNj4uOS9E=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: laravel-secrets
      namespace: uniselec-api
    type: Opaque
