---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: laravel-secrets
  namespace: uniselec-api-prd
spec:
  encryptedData:
    APP_KEY: AgDFVe7YlsmKkYzf0bT124Rvoj/qCxGNS/j+s0Ot4owUNIbShMPs5GZqoZiUrAxvbGzuThjUYuyCMCaZukAdtTqV7qiauH0SBHbemp+Y3/Pdd78YhXIhUccvS4xZYFjjvSCy0z+dIhneY/zLvAAerkEzLEuoqzGodN5jsOmoXQHVqPDoOK4YEPhXazcwOAqCRpi2oUVW8yKO0VqNlNRuedPJ0Pnv4ufN2YgBZnt9/oqKX3koraKQghwi7No2nRBCgvDS0kTKUBK0uWF2i10WIigJMUe7pSZfWxw1opN9Vh3Om3d017+8JV8HLj7oP6II0TcwLv8lC9Tr37wBhykQ7p7wpojt7SZknh+w6tUtJ7veTiVsZDX4BPQ290cdOA2+CECfvw3VDIUuwIcAqXotKPPlZwgSdc2S1NAbx7G+M6otL2YWIMPhrbaAfEQNtdyeOq5nKzQ8SCrwuyG7+a8mL6dEm+FZOCLkXWxb0SbhAr9MoN3lHxNnBmm7O8Yk9tMkay3mrv6fEqrPZKLKI0xRk7+QFBJ1gXjWas3+LaUPWdbjcEI0HJz9kk8gJ8GoeGFZ0/xZAbhDPDGWLOrkvn+9WRvzfFHseIxin12imqIqEuUOBMnbgM9nubR1fZkJT0osG9cbBLmcEyqp2xF2brKwWK4xniXwo3dZvb0LN41CbrhdqAhhFx5hQrDA/FCEzJ6LXARt/OgRAIhh6xGWmgsx01VhH/QjK9donh2LdZ76ykOiutHERaKqJ4+WJ7FJWpsx02H3v9U=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: laravel-secrets
      namespace: uniselec-api-prd
    type: Opaque
