---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: laravel-secrets
  namespace: uniselec-api
spec:
  encryptedData:
    APP_KEY: AgAgxOaxDjtyGl83/rkAIuN9wqafMTOMpdBLlyzZWLvf+acADIqHiUjH6V+yi3kihi+aDzA+mGSssFr5mb3VzP05VWMkjf92h8iEy9wSjMpi8yFOz5iJ3dwfPabbcS/lXu8TvcmTC2zlCa6JJNhhASJ6UoEs8PZjgKgQShl8DfbXMYHYfN1qQ5dCOi3AjL/YvUE8/lUjlzO9XDuroJaI9aPbutOcIAqel95vyS0hdCZXwDXvQ74tP7mLvZzc8mD7i7O6UhDc/8jNe+XOrcv/1d/xSloUn8RuOF0OR1qV6mYFdqR0XxQCxQmkiihbZ1/WluOLXQ42W+iaQW9JGr36w/6hzMAi7955XGFMooKq1e/agUDMp5lcKAd4Q65Rujy4X1pd+ctmgBaToHXnULM3wDyuFtwifkKfGBQmqZKUHN8jIOjgKvQitog/5Da8YYD1wRgDH7Rco3OItRNXtpD7Mw27S3eU69P1zNuUFqN0EdfUjY3PNANn69g+Xw274TsD8U+YISzChJa26W+9r7siYXZ52ciNyrASwehIeogCRLsAecN/QSV9FNIdoGOSjgxcERuhgBQMcFvbWCxZ4RIxgXJTRxItp5S4c4QUAJPOic6ly2C/POFxK5HOL/GY8evQUNI+kNnQvGxGOORx6Qftv6WQWQ984C+K3uPuQLTAZ9WCMQ6DMa0f8dNjbVFaV2AKygJ1zmXmHgyaI1YqrxCR9exfoge/02pPkrJ4CIyrlp8HGf6bQF5HLM5gBteaRenrK0redpU=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: laravel-secrets
      namespace: uniselec-api
    type: Opaque
