# https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.33.1/controller.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: uniselec-api
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: uniselec-api
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 350
      policies:
      - type: Percent
        value: 25
        periodSeconds: 90
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 65
        periodSeconds: 45
      - type: Pods
        value: 1
        periodSeconds: 45
      selectPolicy: Max