apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: regcred
spec:
  encryptedData:
    .dockerconfigjson: AgBwPJgVQGBE4okLehRwAA4ROSh1PZDkKrQVJguPT3xMTVWn404B8/n3SRkLIsFNTtzmaLyMFmBYejRBj3IgjZshBL/aMqb3FFvzgl1xImnHTbNpdaTHJSEYFX6WnUY/xJQ+XCiLIH1MV83PGM6nTx7mAg8d+M3r6XCdKob2+NdRPMs3dOatigUdB/fzB0CsyFldGur2eAeVs+6RKnSK8vf0AgoieOfYwyqylQS5SkUVyF5mvB2tLu/CEBAjEqTQ834WdT8n+cqmt9Gyse6FHj6NnuRa5AJyrG97QrxRj5IBAI6VMeOfYbyQTDCT/mT7qU05MyplCciXEPH+xzWulpmZ3oW/msyrxRNsxGfOghfGXt6l2TJFa1H+AWWne1hsbA6WVMn29c/G6GW45/raP1zR/tZ1GZ5JMiD8/lsDljwJtJHSvI4l+fPn3xHQLGzZRB/gqcYcInAs7b9ce17Sbl6Z8359pp0/3e7Sw3e8f96yCYn+FgD/FxoqhSeNtua90tXlJ+goMp8lnbGsKOhVb+E93TT2agbP4aBU6Z0KmjnoP98hiR54lYz5LhnZca/twc293PY6cJOka4RR6d1uEJC1EMlGAMLpWPGnQLen3bgSQI11uWkuUrYvV1Zw2QlfJhGDi4PyEHBxKh3k6WQ+qsNnVuP3JEu6/4VkqyRLRsuUq7gSgzejRG/dHZMXXBEakQGpkEskWyv9YLs8T6+HM4+6jZtMG0zTiYVIr9iQM1DbSw76YP+0chn1Nqgk75XvWaNTDhpGgZ1vwYXdoG0InNLd8l7uP8KvKg+8R5CAhmduCECcDu9BHiVh1RLzxK7S657EYSa6B1IvxFgKCcWdsZ4Qp7TXVGVNJMdga7fiSNB/yvxzCamcvZdB/mxHOepcYQ8Hplx2S1QcZwqJWSwp5Z1S+3NMhFfMREbb6YXUAHTxWLY7Ud8vfndVBj0d0rAfQ0SVPO4N+LlqTf3X2PG1dP0hI1tyQqNjEwZv6F1/gP9iF9I=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: regcred
    type: kubernetes.io/dockerconfigjson