---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: regcred
  namespace: uniselec-api
spec:
  encryptedData:
    .dockerconfigjson: AgA5TLDVkPdylUScl9XI0EpHhdkVzH20cPXHjIyxQqyiCPwY7PHw5koMnwemcGQY2hDTGyXyXm2zjD+UZRker8undkT0kfA8/Z13hY+n3AEAlEAmRlJh8V5D16dqwSYeVY9WD2A0afP+sP5h3do8HmnpuXZjxdBT2ic5uddP/Dxv9y+Kj3jsFEaGwJw89Io+/yI6V0QsD/VCof3XPQItr8W5OuT17xG+9hxEb9UwOd3JpJpuS8JM6ncdnOVeXLXzsRbKCOQbb+MZCGxIdnrCvCClDuEVW99HIf4f2YTTC/Z8+v8KKfeHIvVVQ1Ebp/13+2/cLcfqaN9I2LACZ3QQiUqTO5VUFUKZZ2QfBEl/ZhjZeEw8slLte4aB48WQLMvI+xjM900oGJUCdjntpaKogBMBa+fnqvicy1j70oiu8yt/T+bKIlcLJvCBb51gcjRSdSJ8Gj00Fvol5jApxd2q8OWjm+kaBg55vGFMfbTaUP9zjQbXzVsQ9KzBGd7KhsadPAgs6Ti8Y5wu/hLm6u32UsSbEZUi5JHv9f1nLHdXCSHqXwq+vWehtoHkB0s014UsU2nD6DJUOhwF0xxMa2L8+5g0aiSbCwPGMKWqR+7HQHI/Nu6/w6c94Par8zPOoyc01ggRAqcrEBXxlyujKhLt/iFLhEAsAsAuwP9cVicsfr+SpAUuWhHBx7wLxaok1Sa9mre0UAfcmoNQlOkKxyhWK1vqzT39N+Ju7HvJ2+jIYtUau5nninaV9vzFcTq/GdwDo0sndZulbqGPPNh0CcJkgMRpMc70jXSsjl7dyWm7Ci8OJCI4rr8lLSCn2DpF16AvuoBZRhQNqNI3MECh8T6aqJmbr+n9XRSHz9JSfm3OfklN4UKTqgi9uf6BcarL+XWdDvwsVlAIvbx6P34h6dqKlCV0itqLo+l/rYW3XmtLw2eBCIIdseg4Y13ope1jFRJomD8w383kee1D8vSvjZVNvXsp
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: regcred
      namespace: uniselec-api
    type: kubernetes.io/dockerconfigjson
