---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: regcred
spec:
  encryptedData:
    .dockerconfigjson: AgCNjO69T2ke0rUsG+yxkzoDOKKZHOfMfdKimjFwBRfMU2WNFK0S6/Vvz7B+SGvJ2U9qw83f3wkmlQBNzuvORL038zeMPaMINN9W3OKojxS9uxewxGgJzYk3qAwFhSzbMuFgGXhbkTMigjU6PucOaWPQYW6jPXUmAMaww3QlHwuTBhXu/b7pJqZXbcKOI8CB8/hjbAYwVsR6NfX2WiFT2KgtGOXBJhwCJRc0aW1PoC/45D3/d5GLChUl8hiWga7D0hXB7j2x7oBPJuy34TYllX0pKAxhJMgoCQpY865hwTvtQKpO+OtJq3S794bSkMTiwfj8dAs7sylum06DMTY5gzgOkT3pcCyijLq+f74Nucwp5TVRqmz6HE7zxMxmO3BflbMoSZCJmKVU501xuCEw8FzIHQ8Ous7O3Z8vxqyGBNjQpvmPUp1ozHwOkQp68zgBSJriEErGAE91SWneiaNIbvLB011/6mX7qcOKrof0kJBGWjcxKIB376ptgK7WNBx1DV0lefnj+oux3KXUveJzEGSpcst6RT9UtCQywfkcVgVk3217DmDaPViJCk3c11MlU1zAYsZlTFBpGqdv/5bZOOSu4XnTg8bmZ7s2cXuHNVI8C7wbXV5EHuBZLQNwCjNe/w2PMwXeQegqj+zudfsZN3g03fpr8w4/gbYS34vyVOB10To9niotP7AwALVXVahMRthA4sqIjNneCEfAF66k1gS+/8M2t55+HZvr2UJI+ZHfGWWFTT8dh2RAp5S1Iv/DKOp7hX2u4pNnGxMqYyd3nTuxnNY6lYyO6YxJl+Yqe8H1i1+Lfbbaqy/OmTZeVSb6O9N2CfaADrox64XQslNFbjvGstu6OdFYRbr4qcWcFVKJU4hJ1fXwb0D/hfBpPVV57D0wwWgfyhxo3UjGY2Tfu3fjPVIc6HmU8fOiqUFFHS+m287IirDsooynuUmKbiEbSv+aIh2Q0PFHIC8a+lBZEkd6BAF4n+oi9SsUx/THztTseJw=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: regcred
    type: kubernetes.io/dockerconfigjson
