---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: regcred
spec:
  encryptedData:
    .dockerconfigjson: AgCgNJk4QYwVWJmqZ/e9JwZgySsmV5o/9gsM+Jy0v7KekXMxGS12KrA2vjNIXg+nSOZPxuNV4t8bKk7vHtA8/D2hr+A8Q1WGOKBneWIs7unIaPnlQWiXfmGuL/y2s3a/5Lw75ACWfXHt9ZJoooHlcg7qESEJ9LS2iCHIgF4RgIWIOF21wr066yTaoniLF/8rJCc1U7E5v6VrEnVf7vEPvLd7fH0sjYXHj3om8V4li3d27s8FNO6UW7YijHxFjsIcad25LiQsX3PNIZd5QLONzbDF1LA2rVwkl+vmmZWkZ72DXP33NO99DFx6TLnz5vLJExHrwauL6T893r9US/7+gylV3ryzgJ7QL9P9J1WvAR/VClXOX9SKfOonGKaX07GV9qNJb5lT7DiND/lAPO5cQ3JucCLNDh6+ueDfncN5g/FnpHGaJ52rkjZYdQzOaZ2++zDA9B7TGF2d/hu9bk0rrDVbupMrUj000ZM4c+A/xMa3jTPhVGYsaeLii91+cyuTOiRxPUyySih4Z0LR/P6w9s8MrIvSocrxwUa0WolSsexyNgYFxwnyals1XcQWXfkU1dhKS3t89RRfWQFHlYnP/d4+QwLyezY63eoQ9+EAXhANSvyI2bEO/v54aQgP44UZGIp9GgTP8jE9OdR/T+aRD7iKed+Hxw1Et9tJjx8Xxjn9ispCXvHJ+PhmFqE/VUD8lE8+sq67UAp58t3pIzKl28Ax264gxPJfkhd3RO6w0yuiIZUai5gUib3jLRTD+DE7enGM5YhF+OMC/zG/Vg9u0ZcHZNdClKMv9H39GGTb6zs7tyyvLy4qGlIdxJMDW900zyPFukIUE7uVCP1Q3JUbsAWR7SO+wV2dwIX91RmpK1PJhWRF44/snrHWz+udysgN4UU7gXmIT33wnaU7Rod6WL6oIreUJU7QQPKssB1X/D1LbMd5oZ3fd1C24yVBw69EsnrfOss0N2X710XKgUoPkXb/4lKCPjSgGg5A7yc=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: regcred
    type: kubernetes.io/dockerconfigjson
