---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: regcred
spec:
  encryptedData:
    .dockerconfigjson: AgAsBCEdfaRY5gKv3M9QFfN59LAilmeXCzh9G3lOnTWTLAoYB1ng2BxFI0Cq9havXu23zNuIzTe+YAwJzB0yk72V/IZiqquTVodXrysHOv/F8fR3JNazqiBWMEw5mGZ3fQrvWLiOXVAJ1gKrdwBwonqzglGhviMI/WPsI4ODIKdXmixfz8Ea31/+jcgobksm8HKvBHAPpIQTYX1aLm0CQNdCo1MKiDLSqtQ1BrfGj1i4DSIaKwvqBH9X4balaMPI7ves00YWMajJjFIEJSYmoYlXEIT0v4YfONv97USnkq8BYrxeX5N04mHiQJabSPcG9vXe+bUyqeXhCegmDzxHGuCZFdvcUrjm/3Yk8SuXY7LOgxctialak7NU57RPQX0lSE7W2fuOFw4FcRASBOZ17ZSjgpigZYz7CXOKFdDBWA2EWOHBXFkN2qQe09UZrYlc4GT0++PUILxydZLLfdnqiy93mpvoVicYt8SBrMZlcyCHQI/H4zvKbjsQDz5/fl3ja4ClyYlH3ChM6PMz5+Ktppi+6TMsq/tVap8VXxs6hbdmh9po6iJXOGIxEKD5ihg8lovABlzoEtAdwQPNJxK/W6Jsq6bllYKSSJo1CxJmonwJYsa34G2JH4cIpjAJobSPdj+WbKNLXoJvp+4QnzhiKL/0lkcPley8lQvad81rxXcn5CAWuLy3sUiMo4BPOijvGPAjQKE/c29MXC75ZgAKq/NjtJlnrl79SRKWG9fyNMCL2Wh/Io8Uj1MbBbYkvKR8k3OxkwYuCPzl4gbIJddNPukSWcEqV31iwQqrZ353vpBg4hdzcKWTONd6ARsa0wDOG59namQU0LHNyT1olnfXOett4JjQbquPdNFFSkgu/gOj6pdCA1mdZT1Kf9PuVoTxKR2jb2gCOeaTAaAh2wN1Y3Sjcf8cJb9dmjQu55m9BF7CmKJrwOLqB4qpWWDMW+fyY4aTLy+uW9Z3J1TPgOMqe3cuJXAzzHTWCD8upZZp9cD0vbSR/jH0w64LP9CWnYl1CoB+lnz8yNbdepeQ2w==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: regcred
    type: kubernetes.io/dockerconfigjson
