apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
spec:
  template:
    spec:
      containers:
        - name: mariadb
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 2Gi
  volumeClaimTemplates:
    - metadata:
        name: database
        labels:
          app: mariadb
      spec:
        accessModes:   
          - ReadWriteOnce
        storageClassName: nfs-storage-k8s-v1
        resources:
          requests:
            storage: 25Gi
