apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  labels:
    environment: staging
spec:
  replicas: 3
  template:
    metadata:
      labels:
        environment: staging
    spec:
      containers:
      - name: mariadb
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
  volumeClaimTemplates:
  - metadata:
      name: database
      labels:
        app: mariadb
      annotations:
        nfs.io/storage-path: ""
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: nfs-storage-k8s-v1
      volumeMode: Filesystem
