apiVersion: v1
kind: Service
metadata:
  name: mariadb-lb
  labels:
    app: mariadb
spec:
  type: NodePort
  selector:
    app: mariadb
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      nodePort: 31036  # NodePort fora da lista existente
